services:
  - type: web
    name: house-haunt-flask
    env: python

    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9

    buildCommand: |
      pip install -r requirements.txt
      flask db upgrade

    startCommand: gunicorn -k eventlet -w 1 --bind 0.0.0.0:$PORT app:app

